# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'reservacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id_smartphone', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'smartphone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Traspaso',
            fields=[
                ('id_traspaso', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'traspaso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=60)),
                ('contraseña', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
    ]
